version: '3.8'

services:
  mvc-db:
    container_name: AgonaSemester-db
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AgonaSemester-db